# .github/workflows/tests.yml
name: Tests

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  RAILS_ENV: test
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  WISE_API_KEY: ${{ secrets.WISE_API_KEY }}
  WISE_PROFILE_ID: ${{ secrets.WISE_PROFILE_ID }}
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  playwright:
      name: playwright
      runs-on: ubicloud-standard-4

      steps:
        - uses: actions/checkout@v4

        - name: Generate cache key
          id: cache-key
          run: |
            CACHE_FALLBACK_KEY="setup-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock', '**/pnpm-lock.yaml') }}-"
            CACHE_KEY="setup-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock', '**/pnpm-lock.yaml') }}-${{ hashFiles('backend/**/*.rb', 'backend/**/*.erb', 'frontend/**/*.ts', 'frontend/**/*.tsx') }}"
            echo "key=$CACHE_KEY" >> $GITHUB_OUTPUT
            echo "cache_fallback_key=$CACHE_FALLBACK_KEY" >> $GITHUB_OUTPUT
            echo "Cache key: $CACHE_KEY"
            echo "Cache Fallback key: $CACHE_FALLBACK_KEY"

        - name: Restore playwright & build deps
          id: restore-cache
          uses: actions/cache/restore@v4
          with:
            path: |
              ~/.cache/ms-playwright
              /home/runner/setup-pnpm/node_modules/.bin/store
              frontend/.next
              node_modules
            key: ${{ steps.cache-key.outputs.key }}
            restore-keys: |
              ${{ steps.cache-key.outputs.cache_fallback_key }}

        - name: Build setup
          uses: ./.github/common/

        - name: Install Playwright system deps
          run: pnpm playwright install-deps chromium

        - name: Install Playwright Browsers (headless shell only)
          run: pnpm playwright install --with-deps --only-shell
          if: steps.restore-cache.outputs.cache-hit != 'true'

        - run: node docker/createCertificate.js

        - run: NODE_ENV=test pnpm run build-next
          shell: bash

        - name: Install foreman
          run: gem install foreman

        - name: Cache playwright & build deps
          uses: actions/cache/save@v4
          with:
            path: |
              ~/.cache/ms-playwright
              /home/runner/setup-pnpm/node_modules/.bin/store
              frontend/.next
              frontend/node_modules
              node_modules
            key: ${{ steps.cache-key.outputs.key }}

        - name: Run docker compose
          run: docker compose -f docker/docker-compose-local-linux.yml up -d

        - name: Run Playwright tests
          run: pnpm playwright test

        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 7
